### ISSUE TITLE
Words and images

### ISSUE THREAD

**Issue by dakom** [ji-devs/ji-cloud-flowcharts#2]
The flowchart in memory game `Words and Images` links to `create-word-list`

However, `create-word-list` doesn't include the flow for selecting an image

On the one hand this makes perfect sense since `create-word-list` and `select-image` are in fact separate components

But on the other hand, it's unclear what's supposed to happen in the higher-level container for both of these.

For example, if they click on the "Images" tab, but there are no cards, then they can't assign an image to anything.

Additionally, what is supposed to happen when they hit "done" from the list - they can still navigate to the "text" tab but it has the "Edit your words on the card" content _within_ the text tab?

**Comment by corinnewo** [comment]
There should not be a case where there are no cards, since the list can only be DONE when there are 2-14 words. As described in the create-word-list.drawio.svg (tab for one list).  The only time that there could be no cards on the right is if they delete the pairs on the right. Perhaps, when it gets down to 2 pairs of cards on the right, we **don't show the delete button** on hover.

After DONE is clicked and the words are on the cards themselves, then going back to the TEXT tab will just have the Jiggling with the 'Edit your words on the cards'. Yes, within the tab. The button to CREATE A NEW LIST is still active within the tab, so if it is clicked, then you can start again with a new list.

**Comment by corinnewo** [comment]
@dakom I have updated the flowchart for creating a word list and displaying the pairs of cards. Added in the conditions when delete and add pair buttons are displayed.

**Comment by dakom** [comment]
What happens if they click the `Images` tab before they've finished adding words?

**Comment by dakom** [comment]
Closing this as per zoom discussion, we simply let them use it as-is, but the "no preview" placeholder in the canvas area should be updated to give more direction, e.g. something like "Add text to create your cards"
